### ISSUE TITLE
TRST

### ISSUE THREAD

**Issue by Frido-Cpp** [firstapostle/Blood#13]
https://github.com/firstapostle/Blood/blob/cc4f4e13f5007be115ed34f6235ba5327e8026ee/blood.py#L57

How do you guarantee legitimacy on this executable?
BTW the Repo link you provided in your README Message is Down....

**Comment by firstapostle** [comment]
You can compile TC.js(in repo)(OPEN SOURCE) and compare these files. Please see all the code (next to this link). It searches for this file - if there is one, nothing will be loaded. BTW this is a method and it's easier for me to plug it in this way.
Thanks for not accusing me of malware - I'm getting tired of it.
![image](https://user-images.githubusercontent.com/96767456/172021293-b2d24451-1477-4768-9048-2f2c87f904c6.png)

**Comment by flage** [comment]
It's not TC.js that this is downloading. That's just another excuse here. If it were just TC.js I see no reason for this download but you keep insisting that this binary is safe and needs to be downloaded. Just blowing a lot of smoke into people eyes. Dude even kept it hidden previously with base64 encoded and eval so people would not see it. xD
