### ISSUE TITLE
This is copy

### ISSUE THREAD

**Issue by ffsgz** [firstapostle/Blood#14]
You skid lmao
Blood is copy of KARMA
https://github.com/HyukIsBack/KARMA-DDoS
And your blood's python code is trash
Noob skid :)

**Comment by firstapostle** [comment]
I'M SO FUCKING SICK OF YOU FUCKING CUNTS. YOU BETTER STICK YOUR FINGERS IN YOUR ASSHOLE INSTEAD OF WRITING HERE
