### ISSUE TITLE
Can attack aws-waf protected website attack fail

### ISSUE THREAD

**Issue by NonameASecret** [firstapostle/Blood#5]
Aws-waf(web application firewall ) firewall website attack fail

**Comment by firstapostle** [comment]
Method?

**Comment by NonameASecret** [comment]
> Method?

All Methods, check below link report

https://check-host.net/check-report/9fe1febk4fd

it return **405 (Method Not Allowed)** error, because aws-waf block our request

**Comment by firstapostle** [comment]
Among other things, it is protected by the CF. I'll try to think of something

**Comment by NonameASecret** [comment]
it protected by aws web application firewall & cf. aws - waf is give **405 (Method Not Allowed) error**, 405 is not cf error

cf can bypass, but aws - waf captcha challenge fail to bypass

**Comment by NonameASecret** [comment]
> Among other things, it is protected by the CF. I'll try to think of something

can you give telegram username or email? i can provide more information about in this case
