### ISSUE TITLE
shitty rat 

### ISSUE THREAD

**Issue by galay180591** [firstapostle/Blood#8]
cleared in 10 seconds if u gonna make malware atleast make it good

**Comment by iLaravel** [comment]
Какое вредоносное ПО ты че долбаеб? Дизассемблером по методу пройдись долбаеб, говоря эти слова ты оскорбляешь меня - создателя метода, такие пидорасы как вы отбиваете желание писать вам что-то. Я нахуй блять специально для тебя скомпилировал эту JS ЧТОБЫ ТЫ не ебался с JavaScript и запуском метода ушлепок. Вы не достойны Blood пидорасы ебанные. Хотели бы мы вам компьютеры спиздит нахуй я бы скрыл бы метод для начала сукин сын блять
