### ISSUE TITLE
!!!MALWARE!!! do not trust this code!

### ISSUE THREAD

**Issue by flage** [firstapostle/Blood#9]
Owner of this project keeps closing issues from people who discovered hidden/obfuscated malware within `blood.py` file.
Do not trust this project!
Related issues:
#4 #6
 Here it downloads infected binary from google drive:
 https://github.com/firstapostle/Blood/blob/bd563a2bf3a7f85e99b3b82d09e9044f558c3420/blood.py#L58

**Comment by iLaravel** [comment]
Disassembly tcp.exe and go kill yourself

**Comment by flage** [comment]
Angry because you got caught?

**Comment by iLaravel** [comment]
u can disassembly this file xd

**Comment by iLaravel** [comment]
and u can check it any antivirus

**Comment by flage** [comment]
Maybe you have no basic information about nodejs? You put it as a prerequisite dependency that should be installed from a trusted sources and not downloaded from a sketchy google drive. 
BTW FYI this binary did get flagged by antivirus. So GG.

**Comment by iLaravel** [comment]
OK XD

**Comment by firstapostle** [comment]
Fucking idiots. There's an open TC.js supersource on githab, look fucking hard and find the malware there.

**Comment by flage** [comment]
It's not TC.js that it is downloading you "idiot". Stop spreading malware here.
